
package:
    name: latnetbuilder
    version: "0.1.0a1"

source:
    path: ../..

build:
    script_env:
        - WITHOUT_WAF
    number: 0

requirements:
    build:
        - python
        - pip
    run:
        - python
        - nodejs
        - ipywidgets>=7.1.0
        - widgetsnbextension>=3.1.0
        - notebook>=5.3.0
        - matplotlib>=2.1.0
        - numexpr

test:
    imports:
        - latnetbuilder



