
package:
    name: latnetbuilder
    version: "2.0.0"

source:
    path: ../..

build:
    script_env:
        - WITHOUT_WAF
        - LATNETBUILDER_INSTALL_DIR
    number: 0

requirements:
    build:
        - python
        - pip
    run:
        - python
        - ipywidgets>=7.1.0
        - widgetsnbextension>=3.1.0
        - notebook>=5.3.0
        - matplotlib>=2.1.0
        - numexpr
        - appmode

test:
    imports:
        - latnetbuilder

about:
  home: https://github.com/umontreal-simul/latnetbuilder
  license: Apache License, Version 2.0
  license_file: LICENSE.md